### PR TITLE
fix: remove len calculation in iterable dataset

### PR DESCRIPTION
**Pull request by sahahner**
Fix.

**Bug**
- In some cases, the self-implemented __len__ property on the NativeGridDataset Class does not return the same number of samples that would be equivalent to that implied by the per_worker_init
- In these cases this leads to things such as validation loop skipped, Hanging at end of a training epoch

**To Reproduce**
The example has the following setup:
- multiple GPU
- no limit on the training batches: `dataloader.limit_batches.training: null`
-> validation epoch is skipped.
- deleting the __len__ function solves this issue

Example of behaviour here: https://mlflow.copernicus-climate.eu/#/compare-runs?runs=%5B%22ab15907c4d5a45dd89a9c708eaea3dbf%22,%22dfb1bfa2d72e49769e28a5a138321006%22,%228731ff0d85bf40cbbe7f313fa22af005%22%5D&experiments=%5B%2281%22%5D

**Additional context**
We don't have any functionality built on top of this function so deleting it is the easiest solution to remove the bug.  
We are considering options to use a dataset class that allows us to calculate/obtain the length of the dataset.

Possible Reviewers:
@Rilwan-Adewoyin

### CODE REVIEW

**Review by Rilwan-Adewoyin — APPROVED** [review]
👍

**Comment by gmertes** [comment]
> We don't have any functionality built on top of this function so deleting it is the easiest solution to remove the bug.

If there is no functionality built on top, why does it cause a bug? :D Is it lightning auto calling this function?

Are you sure deleting it doesn't cause adverse effects elsewhere?

@JesperDramsch should we put this one in first release?

**Comment by sahahner** [comment]
> If there is no functionality built on top, why does it cause a bug? :D Is it lightning auto calling this function?

I do not fully understand why this is causing errors. I know for sure the number of batches is too high as when deleting the function the training epoch starts earlier. @Rilwan-Adewoyin do you have new insights on this one?

> Are you sure deleting it doesn't cause adverse effects elsewhere?

This is a new feature (O(weeks)). The function was not implemented before and the code running smoothly then.
Some colleagues where thinking about building functionality on top of this in the future.

**Review by gmertes — APPROVED** [review]

**Comment by Rilwan-Adewoyin** [comment]
> > If there is no functionality built on top, why does it cause a bug? :D Is it lightning auto calling this function?
> 
> I do not fully understand why this is causing errors. I know for sure the number of batches is too high as when deleting the function the training epoch ends earlier. @Rilwan-Adewoyin do you have new insights on this one?
> 
> > Are you sure deleting it doesn't cause adverse effects elsewhere?
> 
> This is a new feature (O(weeks)). The function was not implemented before and the code running smoothly then. Some colleagues where thinking about building functionality on top of this in the future.

So the reasoning for this was that per_worker_init and __len__ function were not completely aligned although they used similar logic:

- the per_worker_init function imposes that each worker for a model_comm_group must have the same number of batches
- the len function previously returned the number of samples per model_comm_group
- the updated len function now returns number of samples per model_comm_group adjusted for the constraint that the each worker on a model_comm_group returns the same number of elements

Additional context

I also don't think the logic in the per_worker_init is correct in that it enforces each dataloading worker in a model_comm_group to have the same number of samples, whereas it should be the number of samples in a model_comm_group should be distributed across all workers and workers allowed to have different number of samples.

**Pull request merged**
