### PR TITLE
feature: sub hour timesteping

### PR DESCRIPTION
**Pull request by JesperDramsch**
This PR enables sub-hour frequencies and timestep in the `config/data/zarr.yaml`.

As long as anemoi-utils supports the increment (and by extension it is assumed that  anemoi datasets) we can get the correct increment to step through the dataset.

----
📚 Documentation preview 📚: https://anemoi-training--63.org.readthedocs.build/en/63/

### CODE REVIEW

**Comment by mchantry** [comment]
Really cool work, have you tested with one of the hourly datasets to ensure this works for a range of values?

**Comment by JesperDramsch** [comment]
> Really cool work, have you tested with one of the hourly datasets to ensure this works for a range of values?

The 6h ran and as far as I know someone from MeteoSwiss is testing the 10m dataset.

**Review by HCookie — APPROVED** [review]
Other the adding some tests if appropriate, looks good to me

**Comment by dnerini** [comment]
@OpheliaMiralles might want to review this one

**Comment by OpheliaMiralles** [comment]
It works fine for me! Sorry for the delay...

**Review by HCookie — APPROVED** [review]

**Review by mchantry — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
