### PR TITLE
Fixes to callback plots

### LINKED ISSUE #179: `SpectralPlot` callback produces TiB size numpy `_ArrayMemoryError`
### What happened?

When used in the training of a high resolution LAM model (CERRA dataset without thinning, hidden LimitedAreaTriNodes of resolution 8) the `PlotSpectrum`  callback produces
```
 File "xxx/lib/python3.12/site-packages/anemoi/training/diagnostics/callbacks/plot.py", line 1067, in _plot
    fig = plot_power_spectrum(
          ^^^^^^^^^^^^^^^^^^^^
  File "xxx/lib/python3.12/site-packages/anemoi/training/diagnostics/plots.py", line 186, in plot_power_spectrum
    grid_pc_lon, grid_pc_lat = np.meshgrid(regular_pc_lon, regular_pc_lat)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/conda_container_env/lib/python3.12/site-packages/numpy/lib/function_base.py", line 5164, in meshgrid
    output = [x.copy() for x in output]
              ^^^^^^^^
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 288. TiB for an array with shape (4449245, 8898489) and data type float64
srun: error: nid005025: task 0: Exited with exit code 1
```

### What are the steps to reproduce the bug?

Run `anemoi-training train' with a config that has a high resolution dataset and graph and
```yaml
diagnostics:
  plot:
    callbacks:
      - _target_: anemoi.training.diagnostics.callbacks.plot.PlotSpectrum
         # every_n_batches: 100 # Override for batch frequency
         sample_idx: ${diagnostics.plot.sample_idx}
         parameters:
         - z_500
         - tp
         - 2t
         - 10u
         - 10v

```

### Version

0.3.1

### Platform (OS and architecture)

Lumi + singularity container + venv

### Relevant log output

_No response_

### Accompanying data

_No response_

### Organisation

RMI

### PR DESCRIPTION
**Pull request by OpheliaMiralles**
- `plot_histogram`: add `density=True` in call to `np.histogram` in order to get density values and not frequencies;
- `plot_sample`: input precipitation currently does not use the same special colormap as the target/pred precipitation sample, which is fixed in this PR
-  `plot_spectrum`: add `min_delta` argument to the `PlotSpectrum` object to define a lower bound on the delta latitude value used to build the numpy array used for computation of power spectra. The current value is 0.0003 deg, which corresponds to 1km. 

Fixes #179

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](https://bol-claassistant.ecmwf.int:443/ecmwf/anemoi-training?pullRequest=182) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf/anemoi-training?pullRequest=182) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf/anemoi-training?pullRequest=182) it.</sub>

**Comment by OpheliaMiralles** [comment]
@gabrieloks any news on this PR? I think all of the tests should pass now, I updated the code with develop today.

**Comment by gabrieloks** [comment]
> @gabrieloks any news on this PR? I think all of the tests should pass now, I updated the code with develop today.

I plan to test it later today :). I also have some doubts about hard-coding 0.0003 into the code. I think this should be specified in the config files

**Review by gabrieloks — APPROVED** [review]
Looks good to me. Thanks a lot for fixing this !

**Pull request merged**
